name: forge_ai
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_body_atlas: ^0.1.4
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.2.4
  freezed_annotation: ^2.4.4
  go_router: ^17.2.1
  google_fonts: ^8.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  lottie: ^3.3.3
  percent_indicator: ^4.2.5
  phosphor_flutter: ^2.1.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  hive_generator: ^2.0.1
  custom_lint: ^0.6.4
  forge_ai_lints:
    path: tools/forge_ai_lints
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/
